import { increment, selectCount } from "@/stores/reducers/counter/counter";
import Head from "next/head";
import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";

const ClientLayout = ({ children }: any) => {
  const data = useSelector(selectCount);
  const dispath = useDispatch();
  
  return (
    <>
      <Head>
        <title>{JSON.stringify(data)}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default ClientLayout;
